# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
